"""Matriz base de reglas SOD (79 reglas), transcrita literalmente de
SAP_SOD_Analyzer_v640.html (variable SOD_BASE).

Modulos: MM, FI, CO, PP, SD, EWM, HR, TR, BC.
Fuentes citadas en el original: OpenIAM, Xiting, SafePaaS, Deloitte GRC, ACFE.

Se usa para sembrar la tabla SodRule la primera vez (ver seed.py). Un
Administrador puede luego editar, desactivar o agregar reglas desde la UI
sin tocar este archivo.
"""

SOD_BASE_RULES = [
    # ── MM: COMPRAS ──────────────────────────────────────────────
    {"id": "MM-001", "modulo": "MM", "nivel": "CRITICO",
     "desc": "Crear/modificar PO + recibir mercancía (ciclo P2P sin control)",
     "p1": "Creación PO", "t1": ["ME21N", "ME22N", "ME21"], "p2": "Entrada Mercancía", "t2": ["MIGO"]},
    {"id": "MM-002", "modulo": "MM", "nivel": "CRITICO",
     "desc": "Recibir mercancía + registrar factura proveedor (3-way match bypass)",
     "p1": "Entrada Mercancía", "t1": ["MIGO"], "p2": "Factura Proveedor", "t2": ["MIRO", "MIR7", "MIRA", "FB60", "FV60"]},
    {"id": "MM-003", "modulo": "MM", "nivel": "CRITICO",
     "desc": "Crear proveedor + crear Pedido de Compra (proveedor ficticio + PO)",
     "p1": "Maestro Proveedor", "t1": ["FK01", "XK01", "MK01", "BP"], "p2": "Creación PO", "t2": ["ME21N", "ME22N"]},
    {"id": "MM-004", "modulo": "MM", "nivel": "ALTO",
     "desc": "Crear PO + registrar factura proveedor",
     "p1": "Creación PO", "t1": ["ME21N", "ME22N"], "p2": "Factura Proveedor", "t2": ["MIRO", "MIR7", "MIRA"]},
    {"id": "MM-005", "modulo": "MM", "nivel": "ALTO",
     "desc": "Liberar SOLPED + aprobar Pedido de Compra",
     "p1": "Liberación SOLPED", "t1": ["ME54N", "ME55"], "p2": "Aprobación PO", "t2": ["ME28", "ME29N", "ME35"]},
    {"id": "MM-006", "modulo": "MM", "nivel": "ALTO",
     "desc": "Revalorizar material + registrar factura proveedor",
     "p1": "Revalorización", "t1": ["MR21", "MR22"], "p2": "Factura Proveedor", "t2": ["MIRO", "MIR7"]},
    {"id": "MM-007", "modulo": "MM", "nivel": "ALTO",
     "desc": "Maestro de materiales + recepción de mercancía",
     "p1": "Maestro Mat.", "t1": ["MM01", "MM02"], "p2": "Entrada Mercancía", "t2": ["MIGO"]},
    {"id": "MM-008", "modulo": "MM", "nivel": "ALTO",
     "desc": "Liberar factura bloqueada + ejecutar pagos",
     "p1": "Liberar Facturas Bloq.", "t1": ["MRBR"], "p2": "Pagos Proveedores", "t2": ["F110", "F-53", "F-58"]},
    {"id": "MM-009", "modulo": "MM", "nivel": "MEDIO",
     "desc": "Contratos marco + crear Pedidos de Compra",
     "p1": "Contratos Marco", "t1": ["ME31K", "ME32K", "ME31L", "ME32L"], "p2": "Creación PO", "t2": ["ME21N", "ME22N"]},
    {"id": "MM-010", "modulo": "MM", "nivel": "MEDIO",
     "desc": "Precios / info de compras + crear PO",
     "p1": "Precios Compra", "t1": ["MEK1", "MEK2", "ME11", "ME12"], "p2": "Creación PO", "t2": ["ME21N", "ME22N"]},
    {"id": "MM-011", "modulo": "MM", "nivel": "MEDIO",
     "desc": "Maestro proveedor + liberar factura bloqueada",
     "p1": "Maestro Proveedor", "t1": ["FK01", "FK02", "XK01", "XK02", "MK01", "MK02", "BP"], "p2": "Liberar Facturas Bloq.", "t2": ["MRBR"]},
    {"id": "MM-012", "modulo": "MM", "nivel": "MEDIO",
     "desc": "Inventario físico: contar + ajustar diferencias",
     "p1": "Conteo Inventario", "t1": ["MI04", "MI09", "MI10"], "p2": "Ajuste Diferencias", "t2": ["MI07", "MI08"]},

    # ── FI: CONTABILIDAD FINANCIERA ──────────────────────────────
    {"id": "FI-001", "modulo": "FI", "nivel": "CRITICO",
     "desc": "Crear proveedor + ejecutar pagos automáticos (fantasma vendor)",
     "p1": "Maestro Proveedor", "t1": ["FK01", "XK01", "MK01", "BP"], "p2": "Pagos", "t2": ["F110", "F-53", "F-58"]},
    {"id": "FI-002", "modulo": "FI", "nivel": "CRITICO",
     "desc": "Datos bancarios proveedor + ejecutar pagos (desvío de fondos)",
     "p1": "Datos Bancarios Prov.", "t1": ["FI01", "FI02", "FI12", "FIBAN"], "p2": "Pagos", "t2": ["F110", "F-53", "F-58"]},
    {"id": "FI-003", "modulo": "FI", "nivel": "ALTO",
     "desc": "Registrar facturas AP + ejecutar pagos",
     "p1": "Facturas AP", "t1": ["FB60", "MIRO", "F-43"], "p2": "Pagos", "t2": ["F110", "F-53"]},
    {"id": "FI-004", "modulo": "FI", "nivel": "ALTO",
     "desc": "Contabilizar documentos FI + revertirlos",
     "p1": "Contabilización FI", "t1": ["FB01", "FB50", "FBV1", "F-02"], "p2": "Reversión FI", "t2": ["FB08", "FBRA", "F.80"]},
    {"id": "FI-005", "modulo": "FI", "nivel": "ALTO",
     "desc": "Crear activo fijo + contabilizar adquisición/baja",
     "p1": "Maestro Activo Fijo", "t1": ["AS01", "AS02", "AS11"], "p2": "Doc. Activos", "t2": ["AB01", "ABAV", "ABAA", "ABAON", "ABAD"]},
    {"id": "FI-006", "modulo": "FI", "nivel": "ALTO",
     "desc": "Abrir periodos contables + revertir documentos",
     "p1": "Periodos Contables", "t1": ["OB52", "OB29"], "p2": "Reversión masiva", "t2": ["F.80", "FB08"]},
    {"id": "FI-007", "modulo": "FI", "nivel": "ALTO",
     "desc": "Crear cliente + registrar cobros / compensar partidas",
     "p1": "Maestro Cliente", "t1": ["FD01", "XD01", "VD01", "BP"], "p2": "Cobros AR", "t2": ["F-28", "F-32", "F-30"]},
    {"id": "FI-008", "modulo": "FI", "nivel": "ALTO",
     "desc": "Datos bancarios proveedor + emitir cheques manuales",
     "p1": "Datos Bancarios Prov.", "t1": ["FI01", "FI02", "FIBAN"], "p2": "Cheques Manuales", "t2": ["FCH3", "FCH5", "FCH6", "FBZ5"]},
    {"id": "FI-009", "modulo": "FI", "nivel": "MEDIO",
     "desc": "Crear cliente FI + registrar cobros entrantes",
     "p1": "Maestro Cliente FI", "t1": ["FD01", "XD01"], "p2": "Cobros", "t2": ["F-28", "F-32"]},
    {"id": "FI-010", "modulo": "FI", "nivel": "MEDIO",
     "desc": "Crear proveedor + liberar facturas bloqueadas",
     "p1": "Maestro Proveedor", "t1": ["FK01", "XK01", "MK01"], "p2": "Liberar Facturas", "t2": ["MRBR", "FB60"]},
    {"id": "FI-011", "modulo": "FI", "nivel": "MEDIO",
     "desc": "Asiento manual en mayor + modificar plan de cuentas",
     "p1": "Asiento Mayor", "t1": ["FB01", "FB50", "F-02"], "p2": "Plan de Cuentas", "t2": ["FS00", "FSP0", "FSS0"]},
    {"id": "FI-012", "modulo": "FI", "nivel": "MEDIO",
     "desc": "Activo fijo + entrada de mercancía (alta ficticia)",
     "p1": "Doc. Activos", "t1": ["AB01", "ABAV"], "p2": "Entrada Mercancía", "t2": ["MIGO"]},

    # ── CO: CONTROLLING ───────────────────────────────────────────
    {"id": "CO-001", "modulo": "CO", "nivel": "CRITICO",
     "desc": "Revalorizar stocks + ejecutar pagos",
     "p1": "Revalorización", "t1": ["MR21", "MR22"], "p2": "Pagos", "t2": ["F110", "F-53"]},
    {"id": "CO-002", "modulo": "CO", "nivel": "ALTO",
     "desc": "Revalorización de stocks + análisis de costos reales",
     "p1": "Revalorización", "t1": ["MR21", "MR22"], "p2": "Análisis Costos", "t2": ["CKM3PH", "CKMB", "CKU1", "CKM3"]},
    {"id": "CO-003", "modulo": "CO", "nivel": "ALTO",
     "desc": "Reasignación manual de costos + creación de centros de costos",
     "p1": "Reasignación Costos", "t1": ["KB11N", "KB21N", "KB31N", "KB61"], "p2": "Centros de Costos", "t2": ["KS01", "KS02"]},
    {"id": "CO-004", "modulo": "CO", "nivel": "ALTO",
     "desc": "Liquidar ordenes CO + crear/modificar ordenes internas",
     "p1": "Liquidación Ordenes", "t1": ["KO88", "KO8G"], "p2": "Ordenes Internas", "t2": ["KO01", "KO02"]},
    {"id": "CO-005", "modulo": "CO", "nivel": "ALTO",
     "desc": "Planificación de costos + liquidación de proyectos (PS)",
     "p1": "Planificación Costos", "t1": ["KP26", "KP06", "KP96"], "p2": "Liquidación Proyectos", "t2": ["CJ88", "CJB2"]},
    {"id": "CO-006", "modulo": "CO", "nivel": "MEDIO",
     "desc": "Crear centro de costos + reasignación de costos",
     "p1": "Centros de Costos", "t1": ["KS01", "KS02"], "p2": "Reasignación Costos", "t2": ["KB11N", "KB21N"]},
    {"id": "CO-007", "modulo": "CO", "nivel": "MEDIO",
     "desc": "Crear elemento de costo + asiento manual FI",
     "p1": "Elementos de Costo", "t1": ["KA01", "KA02"], "p2": "Asiento Mayor", "t2": ["FB01", "FB50", "F-02"]},
    {"id": "CO-008", "modulo": "CO", "nivel": "MEDIO",
     "desc": "Modificar tarifas de actividad + confirmar ordenes producción",
     "p1": "Tarifas Actividad", "t1": ["KP26", "KBK6"], "p2": "Confirmación OP", "t2": ["CO11N", "CO15"]},

    # ── PP: PRODUCCION ─────────────────────────────────────────────
    {"id": "PP-001", "modulo": "PP", "nivel": "CRITICO",
     "desc": "Modificar lista de materiales (BOM) + liberar orden de producción",
     "p1": "Modificar BOM", "t1": ["CS02", "CS01"], "p2": "Orden Producción", "t2": ["CO01", "CO02", "CO40"]},
    {"id": "PP-002", "modulo": "PP", "nivel": "ALTO",
     "desc": "Confirmar operación producción + contabilizar entrada de mercancía PP",
     "p1": "Confirmación OP", "t1": ["CO11N", "CO15", "CORK"], "p2": "Entrada Mercancía PP", "t2": ["MB31", "MIGO"]},
    {"id": "PP-003", "modulo": "PP", "nivel": "ALTO",
     "desc": "Crear orden de producción + liquidar orden CO",
     "p1": "Crear Orden Prod.", "t1": ["CO01", "CO40", "COOIS"], "p2": "Liquidación Orden", "t2": ["KO88", "CO88"]},
    {"id": "PP-004", "modulo": "PP", "nivel": "ALTO",
     "desc": "Modificar receta / hoja de ruta + confirmar producción",
     "p1": "Receta / Hoja Ruta", "t1": ["CA02", "CA01", "C202", "C201"], "p2": "Confirmación OP", "t2": ["CO11N", "CO15"]},
    {"id": "PP-005", "modulo": "PP", "nivel": "ALTO",
     "desc": "Planificar necesidades MRP + crear PO",
     "p1": "Planificación MRP", "t1": ["MD01", "MD02", "MD51"], "p2": "Creación PO", "t2": ["ME21N", "ME22N"]},
    {"id": "PP-006", "modulo": "PP", "nivel": "MEDIO",
     "desc": "Crear centro de trabajo + crear ordenes de producción",
     "p1": "Centros de Trabajo", "t1": ["CR01", "CR02"], "p2": "Crear Orden Prod.", "t2": ["CO01", "CO40"]},
    {"id": "PP-007", "modulo": "PP", "nivel": "MEDIO",
     "desc": "Modificar BOM + ejecutar MRP",
     "p1": "Modificar BOM", "t1": ["CS02"], "p2": "Planificación MRP", "t2": ["MD01", "MD02"]},
    {"id": "PP-008", "modulo": "PP", "nivel": "MEDIO",
     "desc": "Modificar orden producción + registrar salida de componentes",
     "p1": "Modificar Orden Prod.", "t1": ["CO02"], "p2": "Salida Componentes", "t2": ["MIGO", "MB1A"]},

    # ── SD: VENTAS ──────────────────────────────────────────────────
    {"id": "SD-001", "modulo": "SD", "nivel": "CRITICO",
     "desc": "Gestión de créditos cliente + crear pedidos de venta",
     "p1": "Límites de Crédito", "t1": ["FD32", "FD37", "UKM_BP"], "p2": "Pedidos Venta", "t2": ["VA01", "VA02"]},
    {"id": "SD-002", "modulo": "SD", "nivel": "ALTO",
     "desc": "Crear/modificar cliente + procesar pedidos de venta",
     "p1": "Maestro Cliente", "t1": ["FD01", "XD01", "VD01", "BP"], "p2": "Pedidos Venta", "t2": ["VA01", "VA02"]},
    {"id": "SD-003", "modulo": "SD", "nivel": "ALTO",
     "desc": "Entrega de salida + facturación cliente (OtC sin control)",
     "p1": "Entrega Salida", "t1": ["VL01N", "VL02N"], "p2": "Facturación SD", "t2": ["VF01", "VF04", "VF31"]},
    {"id": "SD-004", "modulo": "SD", "nivel": "ALTO",
     "desc": "Entrega salida + revertir / cancelar entrega",
     "p1": "Entrega Salida", "t1": ["VL01N", "VL31N"], "p2": "Reversa Entrega", "t2": ["VL09"]},
    {"id": "SD-005", "modulo": "SD", "nivel": "ALTO",
     "desc": "Crear cliente + gestionar acuerdos de rebate / descuentos",
     "p1": "Maestro Cliente", "t1": ["FD01", "XD01", "VD01"], "p2": "Rebates / Descuentos", "t2": ["VB01", "VB02", "VBK1", "VBK2", "VBO1"]},
    {"id": "SD-006", "modulo": "SD", "nivel": "ALTO",
     "desc": "Crear pedido venta + registrar cobro / compensar deudores",
     "p1": "Pedidos Venta", "t1": ["VA01", "VA02"], "p2": "Cobros AR", "t2": ["F-28", "F-32", "F-30"]},
    {"id": "SD-007", "modulo": "SD", "nivel": "MEDIO",
     "desc": "Crear pedido venta + emitir nota de crédito",
     "p1": "Pedidos Venta", "t1": ["VA01", "VA02"], "p2": "Notas de Crédito", "t2": ["VA01", "VF01"]},
    {"id": "SD-008", "modulo": "SD", "nivel": "MEDIO",
     "desc": "Facturación SD + contabilizar manualmente en FI",
     "p1": "Facturación SD", "t1": ["VF01", "VF04", "VF31"], "p2": "Asiento Mayor", "t2": ["FB01", "FB50"]},
    {"id": "SD-009", "modulo": "SD", "nivel": "MEDIO",
     "desc": "Crear/modificar lista de precios + crear pedidos de venta",
     "p1": "Condiciones / Precios", "t1": ["VK11", "VK12", "VK13"], "p2": "Pedidos Venta", "t2": ["VA01", "VA02"]},

    # ── EWM: WAREHOUSE MANAGEMENT ─────────────────────────────────
    {"id": "EWM-001", "modulo": "EWM", "nivel": "CRITICO",
     "desc": "Crear orden de transferencia almacén + confirmar y ajustar inventario",
     "p1": "Ordenes Transferencia", "t1": ["LT01", "LT0A", "LT10"], "p2": "Ajuste Inventario WM", "t2": ["LI01N", "LI04", "MI07"]},
    {"id": "EWM-002", "modulo": "EWM", "nivel": "ALTO",
     "desc": "Crear TO salida + confirmar TO (auto-confirmación sin control)",
     "p1": "Crear TO Salida", "t1": ["LT0C", "LT01", "LT31"], "p2": "Confirmar TO", "t2": ["LT12", "LT11", "LT1B"]},
    {"id": "EWM-003", "modulo": "EWM", "nivel": "ALTO",
     "desc": "Entrada de mercancía EWM + ajuste de diferencias de inventario",
     "p1": "Entrada Mercancía EWM", "t1": ["MIGO", "LT0F"], "p2": "Ajuste Diferencias", "t2": ["LI04", "MI07", "MI08"]},
    {"id": "EWM-004", "modulo": "EWM", "nivel": "ALTO",
     "desc": "Modificar estructura de almacén + crear ordenes de transferencia",
     "p1": "Estructura Almacén", "t1": ["LS01N", "LS11"], "p2": "Ordenes Transferencia", "t2": ["LT01", "LT0A"]},
    {"id": "EWM-005", "modulo": "EWM", "nivel": "ALTO",
     "desc": "Crear entrega de salida + confirmar salida de mercancía (WM)",
     "p1": "Entrega Salida WM", "t1": ["VL01N", "LT0C"], "p2": "Conf. Salida Mercancía", "t2": ["VL02N", "LT12"]},
    {"id": "EWM-006", "modulo": "EWM", "nivel": "MEDIO",
     "desc": "Cancelar TO + re-crear TO de entrada (ocultar diferencias)",
     "p1": "Cancelar TO", "t1": ["LT15", "LT16"], "p2": "Crear TO Entrada", "t2": ["LT0F", "LT01"]},
    {"id": "EWM-007", "modulo": "EWM", "nivel": "MEDIO",
     "desc": "Bloquear/desbloquear stock en almacén + crear TO de salida",
     "p1": "Bloqueo Stock WM", "t1": ["LS02N", "LQ02"], "p2": "Crear TO Salida", "t2": ["LT0C", "LT01"]},

    # ── HR: GESTION DE PERSONAL / NOMINA ───────────────────────────
    {"id": "HR-001", "modulo": "HR", "nivel": "CRITICO",
     "desc": "Alta de empleado + ejecución de nómina (empleado fantasma)",
     "p1": "Alta Empleado", "t1": ["PA40", "PA41"], "p2": "Nómina", "t2": ["PC00_M99_CALC", "PU01", "PC00_M13_CALC"]},
    {"id": "HR-002", "modulo": "HR", "nivel": "CRITICO",
     "desc": "Datos bancarios empleado + ejecutar nómina (desvío pago de haberes)",
     "p1": "Datos Banco Empleado", "t1": ["PA30"], "p2": "Nómina", "t2": ["PC00_M99_CALC", "PC00_M13_CALC", "PU01"]},
    {"id": "HR-003", "modulo": "HR", "nivel": "CRITICO",
     "desc": "Modificar sueldo/remuneración + ejecutar nómina sin aprobación",
     "p1": "Cambio Remuneración", "t1": ["PA30", "PA51"], "p2": "Nómina", "t2": ["PC00_M99_CALC", "PC00_M13_CALC"]},
    {"id": "HR-004", "modulo": "HR", "nivel": "ALTO",
     "desc": "Baja de empleado + liquidación final (manipulación indemnización)",
     "p1": "Baja Empleado", "t1": ["PA40"], "p2": "Liquidación Final", "t2": ["PC00_M99_CALC", "PU01"]},
    {"id": "HR-005", "modulo": "HR", "nivel": "ALTO",
     "desc": "Modificar maestro HR + aprobar tiempo/asistencias",
     "p1": "Maestro HR", "t1": ["PA30", "PA20"], "p2": "Aprobación Tiempo", "t2": ["PTMW", "CAT2", "CAT4", "PT60"]},
    {"id": "HR-006", "modulo": "HR", "nivel": "ALTO",
     "desc": "Nómina + contabilización de nómina en FI (manipulación doble)",
     "p1": "Nómina", "t1": ["PC00_M99_CALC", "PC00_M13_CALC"], "p2": "Contabilización Nómina", "t2": ["PC00_M99_CIPE", "PC00_M13_CIPE"]},
    {"id": "HR-007", "modulo": "HR", "nivel": "ALTO",
     "desc": "Crear/modificar empleado + aprobar ausencias / vacaciones",
     "p1": "Alta/Mod. Empleado", "t1": ["PA40", "PA30"], "p2": "Ausencias", "t2": ["PT61", "PT60", "PA30"]},
    {"id": "HR-008", "modulo": "HR", "nivel": "MEDIO",
     "desc": "Estructura organizacional + contratar empleado",
     "p1": "Estructura Org.", "t1": ["PP01", "PP02", "PPOME"], "p2": "Alta Empleado", "t2": ["PA40", "PA41"]},
    {"id": "HR-009", "modulo": "HR", "nivel": "MEDIO",
     "desc": "Gestionar deducciones/conceptos + ejecutar nómina",
     "p1": "Conceptos Nómina", "t1": ["OH11", "PE04"], "p2": "Nómina", "t2": ["PC00_M99_CALC", "PC00_M13_CALC"]},
    {"id": "HR-010", "modulo": "HR", "nivel": "MEDIO",
     "desc": "Evaluación de desempeño + modificar remuneración",
     "p1": "Evaluación Desempeño", "t1": ["PHAP_SEARCH_PA"], "p2": "Cambio Remuneración", "t2": ["PA30", "PA51"]},

    # ── TR: TESORERIA ─────────────────────────────────────────────
    {"id": "TR-001", "modulo": "TR", "nivel": "CRITICO",
     "desc": "Crear operación financiera + confirmar/liquidar operación",
     "p1": "Crear Operación", "t1": ["FTR_CREATE", "FTR_EDIT"], "p2": "Confirmar Operación", "t2": ["FTR_CONFIRM"]},
    {"id": "TR-002", "modulo": "TR", "nivel": "ALTO",
     "desc": "Posición de tesorería + ejecutar pagos manuales",
     "p1": "Posición Tesorería", "t1": ["FF7A", "FF7B"], "p2": "Pagos Manuales", "t2": ["F-53", "F-58", "F110"]},
    {"id": "TR-003", "modulo": "TR", "nivel": "ALTO",
     "desc": "Gestión de garantías bancarias + liberación de pagos",
     "p1": "Garantías Bancarias", "t1": ["FTR_LIMIT"], "p2": "Pagos", "t2": ["F110", "F-53"]},
    {"id": "TR-004", "modulo": "TR", "nivel": "MEDIO",
     "desc": "Previsión de cash flow + operaciones bancarias",
     "p1": "Cash Flow", "t1": ["FF63", "FF67"], "p2": "Operaciones Bancarias", "t2": ["FTR_CREATE", "FF-5"]},
    {"id": "TR-005", "modulo": "TR", "nivel": "MEDIO",
     "desc": "Límites de crédito de contraparte + crear operaciones financieras",
     "p1": "Límites Contraparte", "t1": ["FTR_LIMIT"], "p2": "Crear Operación", "t2": ["FTR_CREATE", "FTR_EDIT"]},

    # ── BC: BASIS Y SEGURIDAD ───────────────────────────────────────
    {"id": "BC-001", "modulo": "BC", "nivel": "CRITICO",
     "desc": "Visualizar tablas (SE16/SE16N) + modificar vistas (SM30)",
     "p1": "Visualizar Tablas", "t1": ["SE16", "SE16N", "SE16H"], "p2": "Modificar Tablas", "t2": ["SM30"]},
    {"id": "BC-002", "modulo": "BC", "nivel": "CRITICO",
     "desc": "Crear/modificar usuarios + asignar roles SAP",
     "p1": "Gestión Usuarios", "t1": ["SU01", "SU10"], "p2": "Gestión Roles", "t2": ["PFCG"]},
    {"id": "BC-003", "modulo": "BC", "nivel": "ALTO",
     "desc": "Crear Queries SAP + visualizar/modificar tablas del sistema",
     "p1": "Queries SAP", "t1": ["SQ01", "SQ02", "SQ03", "SQVI"], "p2": "Tablas Sistema", "t2": ["SE16", "SE16N", "SM30"]},
    {"id": "BC-004", "modulo": "BC", "nivel": "ALTO",
     "desc": "Migración masiva (LSMW/LTMC) + visualizar tablas",
     "p1": "Migración Datos", "t1": ["LSMW", "LTMC"], "p2": "Visualizar Tablas", "t2": ["SE16", "SE16N"]},
    {"id": "BC-005", "modulo": "BC", "nivel": "ALTO",
     "desc": "Abrir periodos contables + ejecutar reversa masiva de documentos",
     "p1": "Periodos Contables", "t1": ["OB52", "OB29"], "p2": "Reversa Masiva", "t2": ["F.80", "FB08"]},
    {"id": "BC-006", "modulo": "BC", "nivel": "ALTO",
     "desc": "Desarrollar / transportar programas ABAP + acceder a tablas",
     "p1": "Desarrollo ABAP", "t1": ["SE38", "SE80", "SE37"], "p2": "Tablas Sistema", "t2": ["SE16", "SE16N", "SM30"]},
    {"id": "BC-007", "modulo": "BC", "nivel": "MEDIO",
     "desc": "Gestionar trabajos batch (SM36) + modificar tablas del sistema",
     "p1": "Jobs Batch", "t1": ["SM36", "SM37"], "p2": "Modificar Tablas", "t2": ["SM30", "SE16N"]},
    {"id": "BC-008", "modulo": "BC", "nivel": "MEDIO",
     "desc": "Gestionar conexiones RFC + acceder a tablas del sistema",
     "p1": "Conexiones RFC", "t1": ["SM59"], "p2": "Tablas Sistema", "t2": ["SE16", "SE16N"]},
]
